### ISSUE TITLE
Qlik sense 3.2.3 issue

### ISSUE THREAD

**Issue by sommagio** [erikwett/qsVariable#17]
Hi, 
unfortunately with the last Qlik Sense release the extension stopped working.

Could you please double check it and eventually fix it.

Many thanks.

Giovanni

**Comment by erikwett** [comment]
Could you please be a bit more specific: what is broken, the rendering or
setting the variable value? Are there any error messages in the browser
console?

Den 20 apr. 2017 4:49 em skrev "sommagio" <notifications@github.com>:

**Comment by AnalyticsEarth** [comment]
HI, the variable is not being set when the value updated in version 3.2.3.

In version 3.2 it was necessary to create the variable first and then add to the extension. with 3.2.3 this does  not work and older apps will show the value of the variable but not update the value when the slider for example is moved.

**Comment by qliktap** [comment]
Hi, this is not working in 3.2+ due to API deprecation. 

As of 3.2+, the variable API no longer has the method `setContent`, you need to use either `setNumValue` or `setStringValue`. 

Also `app.currVal(ext)` does't seem to be referencing the app model correctly. 

As a dirty hack setting a new variable  at the start of variable.js would work

eg: 

`var myApp = qlik.currApp();`

Then replace 
`qlik.currApp(ext).variable.setContent(layout.variableName, this.value);`
 with
`myApp.variable.setStringValue(layout.variableName, this.value);`

(or `alt.value` as appropriate)

**Comment by erikwett** [comment]
Thanks for your help!

I haven't actually managed to get hold of the 3.2.3 release, does anybody know where to download it??

**Comment by GusK77** [comment]
Hello Erik,
Been having the same problem with qsVariable since this morning that I downloaded and installed Qlik Sense Desktop 3.2.3.
It simply doesn't seen to respond to corresponding charts/calculations whatever the selection made.

You can download the installer here [Qlik Sense Desktop 3.2. SR3](https://da3hntz84uekx.cloudfront.net/QlikSenseDesktop/3.2.3/203/_MSI/Qlik_Sense_Desktop_setup.exe)

Please check it out and provide with a solution/update as soon as possible because many of us use and depend on your excellent extension.

Thanks in advance!

**Comment by erikwett** [comment]
Tried debugging this. I get an error in the console:
TypeError: Cannot read property 'getVariableByName' of undefined
    at client.js??1490806788818:61
    at g (require.js?1490806788818:20)
    at require.js?1490806788818:20....
The code that fails is this:
b.prototype.setStringValue = function(b, c) {
        return a(this.app).then(function(a) {
            return a.getVariableByName(b)
        }).then(function(a) {
            return a.setStringValue(c).then(function() {
                return a.getLayout()
            })
        })
    }
(setContent, that is used in the extension, is only a wrapper around setStringValue.

The reason it fails is that the a function (minified name..) returns undefined:
    function a(a) {
        return a.waitForOpen.promise.then(function() {
            return a.enigmaModel
        })
    }
And that is because the enigmaModel is not there.

This is pretty internal in the API, and probably means that the variable API is broken in 3.2 SR3. So the advice is do not upgrade. Most likely this will affect all extensions using the variable API.    

When I try:
var myApp = qlik.currApp();
myApp.variable.setStringValue(...);
I get the same error.

I don't have a solution for this right now, I'll see if I can find anything.

**Comment by AnalyticsEarth** [comment]
Not sure what the issue is but attached is a working version with the correct fixes as created by qliktap. 

[variable.zip](https://github.com/erikwett/qsVariable/files/953045/variable.zip)

**Comment by erikwett** [comment]
OK, that one works.

The change that's really needed is getting the current app really early, at the top of the file (at my first try I did it at the start of the paint method, which did not help). The change from setContent to setStringValue is not really needed. (Should probably be made for other reasons, though).

The fix means that the extension will not work in a mashup with several apps (that's what the ext parameter is for). This is surely not a common scenario, but might exist.

This seems to be some kind of timing issue.

**Comment by qliktap** [comment]
If I have some time, I'll have a look as to why `ext` isn't working properly - as I said, my fix was a dirty hack :)

As for `setContent` - this was deprecated - please do not use this method. 
[https://help.qlik.com/en-US/sense-developer/3.2/Subsystems/APIs/Content/MashupAPI/Methods/set-content-variable-method.htm](https://help.qlik.com/en-US/sense-developer/3.2/Subsystems/APIs/Content/MashupAPI/Methods/set-content-variable-method.htm)

**Comment by erikwett** [comment]
I'll look into it this evening, a possible cause might be that currApp(ext) is broken, in that case removing the ext parmeter might be enough.

As for setContent/setStringValue you have to remember that this is an old extension, it uses setContent because setStringValue was not available when it was first written. Switching to setStringValue would mean that it would not work with Qlik Sense 2.0 any more, since setStringValue was introduced in 2.1. I don't know if that is a problem, is the 2.0 version still in use?

**Comment by erikwett** [comment]
It looks like the problem was with the parameter to qlik.currApp() which has stopped working in the 3.2 SR3 release of Qlik Sense. I have made a minimal fix, so if you have problem with this try the new version.

Note that if you are using the extension in a mashup with multiple apps this will probably not work with the latest version. The only solution for that is to avoid Qlik Sense 3.2 SR3.

**Comment by sommagio** [comment]
It works.

Many thanks.

Have a nice day.

[http://gallery.mailchimp.com/f8b1483e39de9616789ccd518/images/LOGO_EMAIL.png]
Giovanni Somma
Via Iseo 43
25030 Erbusco (BS)
Te. +39.030.7724111
Cell: +39.335.6536759
Sito internet: www.smeup.com<http://smeup.us2.list-manage.com/track/click?u=f8b1483e39de9616789ccd518&id=82f70ffbc7&e=7e80500e30>

Questa e-mail potrebbe contenere informazioni privilegiate o confidenziali.
Se pensa di aver ricevuto questa e-mail per errore, è pregato di contattare il mittente rispondendo a questa stessa dopodiché è pregato di cancellarla immediatamente.

Da: Erik Wetterberg [mailto:notifications@github.com]
Inviato: martedì 25 aprile 2017 18:52
A: erikwett/qsVariable <qsVariable@noreply.github.com>
Cc: Giovanni Somma <giovanni.somma@smeup.com>; Author <author@noreply.github.com>
Oggetto: Re: [erikwett/qsVariable] Qlik sense 3.2.3 issue (#17)


Closed #17<https://github.com/erikwett/qsVariable/issues/17>.
